window.TGT_POSITIONS = [
  { cohort: "graduate", org: "institute", field: "数据", title: "大模型预训练数据算法研究", id: 8726 },
  { cohort: "graduate", org: "institute", field: "具身智能", title: "具身智能基础模型研究", id: 6073 },
  { cohort: "graduate", org: "institute", field: "具身智能", title: "具身智能导航模型研究", id: 8730 },
  { cohort: "graduate", org: "institute", field: "具身智能", title: "具身移动操作基础模型研究", id: 8752 },
  { cohort: "graduate", org: "institute", field: "具身智能", title: "具身仿真与世界模型研究", id: 8720 },
  { cohort: "graduate", org: "institute", field: "多模态", title: "多模态理解与生成模型设计与优化", id: 6037 },
  { cohort: "graduate", org: "institute", field: "语音/数字人", title: "多模态语音交互基础大模型算法研究", id: 8764 },
  { cohort: "graduate", org: "institute", field: "大模型", title: "基础大语言模型", id: 6039 },
  { cohort: "graduate", org: "technology", field: "智能体", title: "代码智能化算法与应用", id: 6027 },
  { cohort: "graduate", org: "technology", field: "语音/数字人", title: "语音驱动下的数字人唇形、表情和肢体动作一体化视频生成研究与应用", id: 8780 },
  { cohort: "graduate", org: "technology", field: "多模态", title: "OmniDialogue：全模态理解和语音对话大模型探索研究", id: 8742 },
  { cohort: "graduate", org: "technology", field: "智能体", title: "角色扮演、代理行为及对抗博弈在 LLM 中的应用探索", id: 8738 },
  { cohort: "graduate", org: "technology", field: "具身智能", title: "复杂几何空间与动态交互场景的移动避障导航算法研究", id: 8776 },
  { cohort: "graduate", org: "technology", field: "具身智能", title: "家庭场景下通用操作能力的具身算法研究", id: 8671 },
  { cohort: "graduate", org: "technology", field: "具身智能", title: "机器人移动操作全身协同控制算法研究", id: 8624 },
  { cohort: "graduate", org: "technology", field: "具身智能", title: "具身机器人全模态 Agentic 系统设计与后训练研究", id: 8645 },
  { cohort: "graduate", org: "technology", field: "AI Infra", title: "大模型云服务推理优化算法研究", id: 8755 },
  { cohort: "graduate", org: "technology", field: "AI Infra", title: "大模型云端 AI Infra 技术创新与探索", id: 8772 },
  { cohort: "graduate", org: "technology", field: "AI Infra", title: "高性能大模型密态训推算法研究", id: 8732 },
  { cohort: "intern", org: "institute", field: "多模态", title: "多模态理解大模型全流程架构探索", id: 8974 },
  { cohort: "intern", org: "institute", field: "具身智能", title: "世界模型与视频生成时空建模研究", id: 8968 },
  { cohort: "intern", org: "institute", field: "语音/数字人", title: "音频大模型全链路交互架构前沿研究", id: 8868 },
  { cohort: "intern", org: "institute", field: "大模型", title: "千亿级大语言模型架构与分布式研究", id: 8881 },
  { cohort: "intern", org: "institute", field: "具身智能", title: "具身智能训练数据评估与配方探索", id: 8942 },
  { cohort: "intern", org: "institute", field: "具身智能", title: "具身移动操作基础模型与泛化控制探索", id: 8940 },
  { cohort: "intern", org: "institute", field: "具身智能", title: "具身仿真数据合成与世界模型探索", id: 8946 },
  { cohort: "intern", org: "institute", field: "具身智能", title: "VLA 模型与通用具身导航架构研究", id: 8932 },
  { cohort: "intern", org: "institute", field: "具身智能", title: "具身世界模型与通用 VLA 大脑架构探索", id: 8795 },
  { cohort: "intern", org: "institute", field: "数据", title: "多模态大模型高质量数据体系研究", id: 8991 },
  { cohort: "intern", org: "institute", field: "数据", title: "多源异构数据的大模型持续预训练算法研究", id: 8996 },
  { cohort: "intern", org: "technology", field: "AI Infra", title: "大模型高吞吐低延迟推理引擎研发", id: 8841 },
  { cohort: "intern", org: "technology", field: "AI Infra", title: "大模型训练与 RL Infra 创新探索研究", id: 8851 },
  { cohort: "intern", org: "technology", field: "智能体", title: "角色扮演、代理行为及对抗博弈在 LLM 中的应用探索", id: 8847 },
  { cohort: "intern", org: "technology", field: "语音/数字人", title: "语音驱动下的数字人唇形、表情和肢体动作一体化视频生成研究与应用", id: 8858 },
  { cohort: "intern", org: "technology", field: "多模态", title: "OmniDialogue：全模态理解和语音对话大模型探索研究", id: 8855 },
  { cohort: "intern", org: "technology", field: "智能体", title: "CodeAI 代码大模型全链路与推理优化", id: 8883 },
  { cohort: "intern", org: "technology", field: "具身智能", title: "空间智能增强的具身端到端操作大模型探索研究", id: 8798 },
  { cohort: "intern", org: "technology", field: "具身智能", title: "机器人移动操作全身协同控制算法研究", id: 8805 },
  { cohort: "intern", org: "technology", field: "具身智能", title: "Test", id: 10000 },
  { cohort: "intern", org: "technology", field: "具身智能", title: "复杂几何空间与动态交互场景的移动避障导航算法研究", id: 8811 },
];
