window.SITE_CONTENT = {
  brand: {
    first: "Sherry",
    accent: "Feng",
  },
  links: {
    aboutTgt: "about-tgt/",
    research: "https://research.joyai.com/",
    email: "mailto:fengxiaojing.sherry@jd.com",
    campusPositionBase: "https://campus.jd.com/#/details?id=",
    joyVideoEdit: "https://research.joyai.com/joy-video-edit",
    joyVlInteraction: "https://research.joyai.com/joyai-vl-interaction",
    joyAiEcho: "https://research.joyai.com/joyai-echo",
    joyAiImageEdit: "https://research.joyai.com/joyai-image-edit",
    joyAiVoice: "https://research.joyai.com/joyai-voice",
    eccv2026: "https://research.joyai.com/blog/eccv-2026-papers",
    iros2026: "https://research.joyai.com/blog/iros-2026-papers",
    icml2026: "https://research.joyai.com/blog/icml-2026-papers",
    acmMm2026: "https://research.joyai.com/blog/acm-mm-2026-papers",
  },
  home: {
    photo: "/assets/sherry-feng.jpg",
    photoAlt: "冯晓晴 Sherry Feng",
    nameChinese: "冯晓晴",
    nameEnglish: "Sherry Feng",
    organization: "探索研究院 & 京东科技",
    role: "TGT 招聘负责人",
    summary: "寻找那些愿意把好奇心变成技术突破的人。连接顶尖青年人才与京东前沿 AI 研究机会，一起探索智能的下一站。",
    primaryAction: "探索 TGT 机会",
    contactAction: "联系 Sherry",
  },
  about: {
    hero: {
      kicker: "JD TGT · 2027",
      titlePrefix: "Tech",
      titleAccent: "Genius",
      titleSuffix: "Team",
      summary: "TGT 是京东面向全球优秀青年技术人才打造的顶尖人才计划，与一流团队一起探索 AI 的下一条边界。",
      openLabel: "开放课题",
      departmentsLabel: "核心部门",
      directionsLabel: "前沿方向",
      action: "查看开放课题",
    },
    mission: {
      lead: "我们寻找对未知保持兴奋、对难题保持耐心的 Tech Genius。",
      titleLineOne: "在真实产业场景中，",
      titleLineTwo: "探索技术的下一条边界。",
    },
    work: {
      heading: "代表性成果",
      modelsTab: "模型成果",
      papersTab: "论文成果",
      portalAction: "前往 JoyAI 研究门户",
    },
    positions: {
      heading: "TGT 课题投递",
      note: "选择感兴趣的方向，点击即可前往京东校园招聘官网投递。",
      graduateTab: "应届生课题",
      internTab: "实习生课题",
      allTeams: "全部团队",
      institute: "探索研究院",
      technology: "京东科技",
      searchPlaceholder: "搜索课题关键词",
      allDirections: "全部方向",
    },
    contact: {
      heading: "关于 TGT，还有问题？",
      action: "联系 Sherry",
    },
  },
  aboutMe: {
    subtitle: "xxxx",
    mission: {
      label: "Mission",
      highlight: "xxxx",
      description: "xxxx",
    },
    experience: {
      label: "Experience",
      items: [
        {
          period: "xxxx",
          company: "xxxx",
          title: "xxxx",
          description: "xxxx",
          tags: ["xxxx", "xxxx", "xxxx"],
        },
        {
          period: "xxxx",
          company: "xxxx",
          title: "xxxx",
          description: "xxxx",
          tags: ["xxxx", "xxxx"],
        },
      ],
    },
    education: {
      label: "Education",
      items: [
        { period: "xxxx", school: "xxxx", description: "xxxx" },
        { period: "xxxx", school: "xxxx", description: "xxxx" },
      ],
    },
    contact: {
      label: "Connect",
      items: [
        { label: "Email", value: "fengxiaojing.sherry@jd.com", href: "mailto:fengxiaojing.sherry@jd.com" },
        { label: "WeChat", value: "xxxx", href: "" },
      ],
    },
  },
};
